### ISSUE TITLE
Guide doesn't provide a clear python version to use

### ISSUE THREAD

**Issue by Deivitto** [ConsenSysDiligence/napalm#3]
Same line, different text, I guess is 3.12 as both lines suggest some version or higher:
- Python 3.12 https://github.com/ConsenSysDiligence/napalm/blob/main/docs/running-with-napalm.md#install-napalm
- Python 3.10 https://github.com/ConsenSysDiligence/napalm/blob/main/docs/module-hacker.md#install-napalm

**Comment by JoranHonig** [comment]
good catch!

it should've been python 3.12, I just fixed it 🚀  thanks for the issue
